[versions]
kotlin = "1.9.0"

[libraries]

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.7.2" }

jetbrains-annotations-jvm = { module = "org.jetbrains:annotations", version = "24.0.1" }
